services:
  tor-proxy-admin:
    build: .
    container_name: tor-proxy-with-admin
    ports:
      - "8080:8080"  # HTTP proxy port
      - "4444:4444"  # HAProxy stats
      - "5000:5000"  # Admin panel
    volumes:
      - tor_data:/var/local/tor
    restart: unless-stopped
    networks:
      - tor_network

networks:
  tor_network:
    driver: bridge

volumes:
  tor_data:
